name: Update Google Sheet Data Daily

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 6 * * *'  # every day at 6 AM UTC
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create fetch script and install dependencies
        run: |
          # Create package.json with node-fetch dependency
          echo '{ "type": "module", "dependencies": { "node-fetch": "^3.3.2" } }' > package.json

          npm install

          # Write the fetch script
          cat <<'EOF' > fetch-data.mjs
          import fetch from 'node-fetch';
          import fs from 'fs';

          const API_KEY = 'AIzaSyBWq6_OOSDWjRS5j5Oco-TRAFtZRGMnwPA';
          const SHEET_ID = '1ik-hGF90uWHn2UCbzIJIQO_qhCTvhT1YTB4KH1C9-xQ';
          const RANGE = 'alldata!A2:D';

          const url = `https://sheets.googleapis.com/v4/spreadsheets/${SHEET_ID}/values/${RANGE}?key=${API_KEY}`;

          const run = async () => {
          try {
            const res = await fetch(url);
            if (!res.ok) {
              const errorDetails = await res.text();
              throw new Error(`HTTP ${res.status}: ${errorDetails}`);
            }
            const json = await res.json();
            fs.writeFileSync('data.json', JSON.stringify(json, null, 2));
            console.log('✅ Successfully updated data.json');
          } catch (err) {
            console.error(`❌ Failed to fetch data from ${url}:`, err.message);
            if (err.response) {
              console.error('Response details:', err.response.data);
              }
            process.exit(1);
            }
          };
          run();
          EOF

          # Run the script
          node fetch-data.mjs
        env:
          API_KEY: AIzaSyBWq6_OOSDWjRS5j5Oco-TRAFtZRGMnwPA
          SHEET_ID: 1ik-hGF90uWHn2UCbzIJIQO_qhCTvhT1YTB4KH1C9-xQ
          
      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data.json
          git commit -m "Update data.json from Google Sheets" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
  
